# ------------------------------------------------ COMMENTAIRES ----------------

### cree un comm
POST http://localhost:3000/parfums/2/commentaires
Content-Type: application/json

{
  "content": "c la premier x que je sent bon de ma vie!",
  "rating": 5,
  "userId": 6
}

### Get commentaires for parfum 2
GET http://localhost:3000/parfums/2/commentaires

### delete commentaire
DELETE http://localhost:3000/commentaires/1