 ------------------------------------------------ PARFUMS ----------------
### CREE parfum 1
POST http://localhost:3000/parfums
Content-Type: application/json

{
  "name": "Sauvage",
  "brand": "Dior",
  "price": 120
}

### CREE parfum2
POST http://localhost:3000/parfums
Content-Type: application/json

{
  "name": "CHANELL",
  "brand": "okok",
  "price": 120
}


### voir TOUT les parfum
GET http://localhost:3000/parfums

### voir UN les parfum
GET http://localhost:3000/parfums/1

### Update
PATCH http://localhost:3000/parfums/1
Content-Type: application/json

{
  "price": 99
}

### Delete
DELETE http://localhost:3000/parfums/1
