 ------------------------------------------------ PARFUMS ----------------
### CREE parfum 1
POST http://localhost:3000/parfums
Content-Type: application/json

{
  "name": "Sauvage",
  "brand": "Dior",
  "price": 120
}

### CREE parfum2
POST http://localhost:3000/parfums
Content-Type: application/json

{
  "name": "COCO Mademoiselle",
  "brand": "Chanel",
  "price": 180,
  "description": "best one in the game",
  "imageUrl": "https://www.holtrenfrew.com/fr/Produits/Femmes/Beaut%C3%A9/Fragrances/Parfums/CHANEL-Eau-de-parfum-Intense-vaporisateur/p/20061457002?srsltid=AfmBOook8S4QXZs-KPnGQatqlbBWmzMN7fkoCgRscFHRZE3Vx5ABmOjM"
}


### voir TOUT les parfum
GET http://localhost:3000/parfums

### voir UN les parfum
GET http://localhost:3000/parfums/5

### Update
PATCH http://localhost:3000/parfums/5
Content-Type: application/json

{
  "price": 99
}

### Delete
DELETE http://localhost:3000/parfums/4
