 ------------------------------------------------ USERS ----------------
### pour voir tout les users ! 
GET http://localhost:3000/auth
 
### cree user (change admin a true ou false dans user.entity) (pas admin en bas)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "yanis",
  "email": "yanis26x@hotmail.com",
  "password": "mdp"

}

### pour signIN en admin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "yanis26x@hotmail.com",
  "password": "mdp"
}

### pour signOUT
POST http://localhost:3000/auth/signout

###pour savoir tes qui 
GET http://localhost:3000/auth/whoami

### delete user
DELETE http://localhost:3000/auth/6

### delete TOUT LES USERS
DELETE http://localhost:3000/auth

### get info user id 
GET http://localhost:3000/auth/2

### FAIRE PATCH

//---------PAS ADMIN--------------------
### cree user pas admin (change admin a true ou false dans user.entity)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "pasAdmin",
  "email": "noAdmin@mail.com",
  "password": "mdp"
}


### pour signIN en pas admin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "noAdmin@mail.com",
  "password": "mdp"
}





### cree user pas admin (change admin a true ou false dans user.entity)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "sara",
  "email": "sara@test.com",
  "password": "mdp"
}
