 ------------------------------------------------ USERS ----------------
### pour voir tout les users ! 
GET http://localhost:3000/auth
 

### cree user 1
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "sara",
  "email": "sara5@test.com",
  "password": "mdp"

}


### pour signIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "sara5@test.com",
  "password": "mdp"
}


### cree user test 2
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "nassim",
  "email": "nassim25x@mail.com",
  "password": "mdp"
}


### get info user id 2
GET http://localhost:3000/auth/2

### FAIRE PATCH


### delete user 2
DELETE http://localhost:3000/auth/11

### delete TOUT LES USERS
DELETE http://localhost:3000/auth
