### test
GET http://localhost:3000/users
 
### Create user test
 
POST http://localhost:3000/users
Content-Type: application/json
 
 
{
    "email" : "yanis26x@mail.com" ,
    "password" : "mdp",
    "name" : "yanis"
}